// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file proto/user/user.proto (package user, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/user/user.proto.
 */
export const file_proto_user_user: GenFile = /*@__PURE__*/
  fileDesc("ChVwcm90by91c2VyL3VzZXIucHJvdG8SBHVzZXIiBwoFRW1wdHkiwAEKBFVzZXISCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRINCgVlbWFpbBgDIAEoCRIVCg1lbWFpbFZlcmlmaWVkGAQgASgIEgwKBHJvbGUYBSABKAkSDgoGYmFubmVkGAYgASgIEhEKCWJhblJlYXNvbhgHIAEoCRISCgpiYW5FeHBpcmVzGAggASgJEg0KBWltYWdlGAkgASgJEhEKCWNyZWF0ZWRBdBgKIAEoCRIRCgl1cGRhdGVkQXQYCyABKAkyMQoLVXNlclNlcnZpY2USIgoHR2V0VXNlchILLnVzZXIuRW1wdHkaCi51c2VyLlVzZXJCQFo+Z2l0aHViLmNvbS9HYWJvLWRpdi9iaW5nby9wYWNrYWdlcy9wcm90b2J1Zi9nby9wcm90by91c2VyO3VzZXJiBnByb3RvMw");

/**
 * @generated from message user.Empty
 */
export type Empty = Message<"user.Empty"> & {
};

/**
 * Describes the message user.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_proto_user_user, 0);

/**
 * @generated from message user.User
 */
export type User = Message<"user.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: bool emailVerified = 4;
   */
  emailVerified: boolean;

  /**
   * @generated from field: string role = 5;
   */
  role: string;

  /**
   * @generated from field: bool banned = 6;
   */
  banned: boolean;

  /**
   * @generated from field: string banReason = 7;
   */
  banReason: string;

  /**
   * @generated from field: string banExpires = 8;
   */
  banExpires: string;

  /**
   * @generated from field: string image = 9;
   */
  image: string;

  /**
   * @generated from field: string createdAt = 10;
   */
  createdAt: string;

  /**
   * @generated from field: string updatedAt = 11;
   */
  updatedAt: string;
};

/**
 * Describes the message user.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_proto_user_user, 1);

/**
 * @generated from service user.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc user.UserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof UserSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_user_user, 0);

