// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file proto/user/user.proto (package user, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/user/user.proto.
 */
export const file_proto_user_user: GenFile = /*@__PURE__*/
  fileDesc("ChVwcm90by91c2VyL3VzZXIucHJvdG8SBHVzZXIiBwoFRW1wdHkiwAEKBFVzZXISCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRINCgVlbWFpbBgDIAEoCRIVCg1lbWFpbFZlcmlmaWVkGAQgASgIEgwKBHJvbGUYBSABKAkSDgoGYmFubmVkGAYgASgIEhEKCWJhblJlYXNvbhgHIAEoCRISCgpiYW5FeHBpcmVzGAggASgJEg0KBWltYWdlGAkgASgJEhEKCWNyZWF0ZWRBdBgKIAEoCRIRCgl1cGRhdGVkQXQYCyABKAkiNAoQUGF5bWVudE1ldGhvZFJlcRISCgptZXRob2RUeXBlGAEgASgJEgwKBGRhdGEYAiABKAwiQAoQUGF5bWVudE1ldGhvZFJlcxIKCgJpZBgBIAEoCRISCgptZXRob2RUeXBlGAIgASgJEgwKBGRhdGEYAyABKAwiaQoLVHJhbnNhY3Rpb24SCgoCaWQYASABKAkSEAoIbWV0aG9kSWQYAiABKAkSDgoGYW1vdW50GAMgASgBEiwKCGRhdGV0aW1lGAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCI8ChFQYXltZW50TWV0aG9kTGlzdBInCgdtZXRob2RzGAEgAygLMhYudXNlci5QYXltZW50TWV0aG9kUmVzIjUKD1RyYW5zYWN0aW9uTGlzdBIiCgdoaXN0b3J5GAEgAygLMhEudXNlci5UcmFuc2FjdGlvbjLiAQoLVXNlclNlcnZpY2USIgoHR2V0VXNlchILLnVzZXIuRW1wdHkaCi51c2VyLlVzZXISNwoQQWRkUGF5bWVudE1ldGhvZBIWLnVzZXIuUGF5bWVudE1ldGhvZFJlcRoLLnVzZXIuRW1wdHkSOQoRR2V0UGF5bWVudE1ldGhvZHMSCy51c2VyLkVtcHR5GhcudXNlci5QYXltZW50TWV0aG9kTGlzdBI7ChVHZXRUcmFuc2FjdGlvbkhpc3RvcnkSCy51c2VyLkVtcHR5GhUudXNlci5UcmFuc2FjdGlvbkxpc3RCQFo+Z2l0aHViLmNvbS9HYWJvLWRpdi9iaW5nby9wYWNrYWdlcy9wcm90b2J1Zi9nby9wcm90by91c2VyO3VzZXJiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message user.Empty
 */
export type Empty = Message<"user.Empty"> & {
};

/**
 * Describes the message user.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_proto_user_user, 0);

/**
 * @generated from message user.User
 */
export type User = Message<"user.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: bool emailVerified = 4;
   */
  emailVerified: boolean;

  /**
   * @generated from field: string role = 5;
   */
  role: string;

  /**
   * @generated from field: bool banned = 6;
   */
  banned: boolean;

  /**
   * @generated from field: string banReason = 7;
   */
  banReason: string;

  /**
   * @generated from field: string banExpires = 8;
   */
  banExpires: string;

  /**
   * @generated from field: string image = 9;
   */
  image: string;

  /**
   * @generated from field: string createdAt = 10;
   */
  createdAt: string;

  /**
   * @generated from field: string updatedAt = 11;
   */
  updatedAt: string;
};

/**
 * Describes the message user.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_proto_user_user, 1);

/**
 * @generated from message user.PaymentMethodReq
 */
export type PaymentMethodReq = Message<"user.PaymentMethodReq"> & {
  /**
   * @generated from field: string methodType = 1;
   */
  methodType: string;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message user.PaymentMethodReq.
 * Use `create(PaymentMethodReqSchema)` to create a new message.
 */
export const PaymentMethodReqSchema: GenMessage<PaymentMethodReq> = /*@__PURE__*/
  messageDesc(file_proto_user_user, 2);

/**
 * @generated from message user.PaymentMethodRes
 */
export type PaymentMethodRes = Message<"user.PaymentMethodRes"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string methodType = 2;
   */
  methodType: string;

  /**
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;
};

/**
 * Describes the message user.PaymentMethodRes.
 * Use `create(PaymentMethodResSchema)` to create a new message.
 */
export const PaymentMethodResSchema: GenMessage<PaymentMethodRes> = /*@__PURE__*/
  messageDesc(file_proto_user_user, 3);

/**
 * @generated from message user.Transaction
 */
export type Transaction = Message<"user.Transaction"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string methodId = 2;
   */
  methodId: string;

  /**
   * @generated from field: double amount = 3;
   */
  amount: number;

  /**
   * @generated from field: google.protobuf.Timestamp datetime = 4;
   */
  datetime?: Timestamp;
};

/**
 * Describes the message user.Transaction.
 * Use `create(TransactionSchema)` to create a new message.
 */
export const TransactionSchema: GenMessage<Transaction> = /*@__PURE__*/
  messageDesc(file_proto_user_user, 4);

/**
 * @generated from message user.PaymentMethodList
 */
export type PaymentMethodList = Message<"user.PaymentMethodList"> & {
  /**
   * @generated from field: repeated user.PaymentMethodRes methods = 1;
   */
  methods: PaymentMethodRes[];
};

/**
 * Describes the message user.PaymentMethodList.
 * Use `create(PaymentMethodListSchema)` to create a new message.
 */
export const PaymentMethodListSchema: GenMessage<PaymentMethodList> = /*@__PURE__*/
  messageDesc(file_proto_user_user, 5);

/**
 * @generated from message user.TransactionList
 */
export type TransactionList = Message<"user.TransactionList"> & {
  /**
   * @generated from field: repeated user.Transaction history = 1;
   */
  history: Transaction[];
};

/**
 * Describes the message user.TransactionList.
 * Use `create(TransactionListSchema)` to create a new message.
 */
export const TransactionListSchema: GenMessage<TransactionList> = /*@__PURE__*/
  messageDesc(file_proto_user_user, 6);

/**
 * @generated from service user.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc user.UserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof UserSchema;
  },
  /**
   * @generated from rpc user.UserService.AddPaymentMethod
   */
  addPaymentMethod: {
    methodKind: "unary";
    input: typeof PaymentMethodReqSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc user.UserService.GetPaymentMethods
   */
  getPaymentMethods: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof PaymentMethodListSchema;
  },
  /**
   * @generated from rpc user.UserService.GetTransactionHistory
   */
  getTransactionHistory: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof TransactionListSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_user_user, 0);

