// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file proto/user/user.proto (package user, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/user/user.proto.
 */
export const file_proto_user_user: GenFile = /*@__PURE__*/
  fileDesc("ChVwcm90by91c2VyL3VzZXIucHJvdG8SBHVzZXIiBwoFRW1wdHkiwAEKBFVzZXISCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRINCgVlbWFpbBgDIAEoCRIVCg1lbWFpbFZlcmlmaWVkGAQgASgIEgwKBHJvbGUYBSABKAkSDgoGYmFubmVkGAYgASgIEhEKCWJhblJlYXNvbhgHIAEoCRISCgpiYW5FeHBpcmVzGAggASgJEg0KBWltYWdlGAkgASgJEhEKCWNyZWF0ZWRBdBgKIAEoCRIRCgl1cGRhdGVkQXQYCyABKAkiNAoQUGF5bWVudE1ldGhvZFJlcRISCgptZXRob2RUeXBlGAEgASgJEgwKBGRhdGEYAiABKAwiQAoQUGF5bWVudE1ldGhvZFJlcxIKCgJpZBgBIAEoCRISCgptZXRob2RUeXBlGAIgASgJEgwKBGRhdGEYAyABKAwiPAoRUGF5bWVudE1ldGhvZExpc3QSJwoHbWV0aG9kcxgBIAMoCzIWLnVzZXIuUGF5bWVudE1ldGhvZFJlczKlAQoLVXNlclNlcnZpY2USIgoHR2V0VXNlchILLnVzZXIuRW1wdHkaCi51c2VyLlVzZXISNwoQQWRkUGF5bWVudE1ldGhvZBIWLnVzZXIuUGF5bWVudE1ldGhvZFJlcRoLLnVzZXIuRW1wdHkSOQoRR2V0UGF5bWVudE1ldGhvZHMSCy51c2VyLkVtcHR5GhcudXNlci5QYXltZW50TWV0aG9kTGlzdEJAWj5naXRodWIuY29tL0dhYm8tZGl2L2JpbmdvL3BhY2thZ2VzL3Byb3RvYnVmL2dvL3Byb3RvL3VzZXI7dXNlcmIGcHJvdG8z");

/**
 * @generated from message user.Empty
 */
export type Empty = Message<"user.Empty"> & {
};

/**
 * Describes the message user.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_proto_user_user, 0);

/**
 * @generated from message user.User
 */
export type User = Message<"user.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: bool emailVerified = 4;
   */
  emailVerified: boolean;

  /**
   * @generated from field: string role = 5;
   */
  role: string;

  /**
   * @generated from field: bool banned = 6;
   */
  banned: boolean;

  /**
   * @generated from field: string banReason = 7;
   */
  banReason: string;

  /**
   * @generated from field: string banExpires = 8;
   */
  banExpires: string;

  /**
   * @generated from field: string image = 9;
   */
  image: string;

  /**
   * @generated from field: string createdAt = 10;
   */
  createdAt: string;

  /**
   * @generated from field: string updatedAt = 11;
   */
  updatedAt: string;
};

/**
 * Describes the message user.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_proto_user_user, 1);

/**
 * @generated from message user.PaymentMethodReq
 */
export type PaymentMethodReq = Message<"user.PaymentMethodReq"> & {
  /**
   * @generated from field: string methodType = 1;
   */
  methodType: string;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message user.PaymentMethodReq.
 * Use `create(PaymentMethodReqSchema)` to create a new message.
 */
export const PaymentMethodReqSchema: GenMessage<PaymentMethodReq> = /*@__PURE__*/
  messageDesc(file_proto_user_user, 2);

/**
 * @generated from message user.PaymentMethodRes
 */
export type PaymentMethodRes = Message<"user.PaymentMethodRes"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string methodType = 2;
   */
  methodType: string;

  /**
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;
};

/**
 * Describes the message user.PaymentMethodRes.
 * Use `create(PaymentMethodResSchema)` to create a new message.
 */
export const PaymentMethodResSchema: GenMessage<PaymentMethodRes> = /*@__PURE__*/
  messageDesc(file_proto_user_user, 3);

/**
 * @generated from message user.PaymentMethodList
 */
export type PaymentMethodList = Message<"user.PaymentMethodList"> & {
  /**
   * @generated from field: repeated user.PaymentMethodRes methods = 1;
   */
  methods: PaymentMethodRes[];
};

/**
 * Describes the message user.PaymentMethodList.
 * Use `create(PaymentMethodListSchema)` to create a new message.
 */
export const PaymentMethodListSchema: GenMessage<PaymentMethodList> = /*@__PURE__*/
  messageDesc(file_proto_user_user, 4);

/**
 * @generated from service user.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc user.UserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof UserSchema;
  },
  /**
   * @generated from rpc user.UserService.AddPaymentMethod
   */
  addPaymentMethod: {
    methodKind: "unary";
    input: typeof PaymentMethodReqSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc user.UserService.GetPaymentMethods
   */
  getPaymentMethods: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof PaymentMethodListSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_user_user, 0);

