// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGame = `-- name: CreateGame :one
INSERT INTO game (
  "name", 
  "start", 
  "open", 
  "cardPrice", 
  "maxPlayers", 
  "gameTypeId", 
  "createdAt", 
  "updatedAt"
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, name, start, open, "cardPrice", "maxPlayers", "gameTypeId", "createdAt", "updatedAt"
`

type CreateGameParams struct {
	Name       string
	Start      pgtype.Timestamp
	Open       bool
	CardPrice  pgtype.Numeric
	MaxPlayers int32
	GameTypeId int64
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.Name,
		arg.Start,
		arg.Open,
		arg.CardPrice,
		arg.MaxPlayers,
		arg.GameTypeId,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Start,
		&i.Open,
		&i.CardPrice,
		&i.MaxPlayers,
		&i.GameTypeId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :one
DELETE FROM game WHERE "id" = $1 RETURNING id, name, start, open, "cardPrice", "maxPlayers", "gameTypeId", "createdAt", "updatedAt"
`

func (q *Queries) DeleteGame(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRow(ctx, deleteGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Start,
		&i.Open,
		&i.CardPrice,
		&i.MaxPlayers,
		&i.GameTypeId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const editGame = `-- name: EditGame :one
UPDATE game SET 
  "name" = coalesce($2, "name"), 
  "start" = coalesce($3, "start"), 
  "open" = coalesce($4, "open"),
  "cardPrice" = coalesce($5, "cardPrice"),
  "maxPlayers" = coalesce($6, "maxPlayers"),
  "gameTypeId" = coalesce($7, "gameTypeId"),
  "createdAt" = coalesce($8, "createdAt"), 
  "updatedAt" = coalesce($9, "updatedAt")
 WHERE "id" = $1 RETURNING id, name, start, open, "cardPrice", "maxPlayers", "gameTypeId", "createdAt", "updatedAt"
`

type EditGameParams struct {
	ID         int64
	Name       pgtype.Text
	Start      pgtype.Timestamp
	Open       pgtype.Bool
	CardPrice  pgtype.Numeric
	MaxPlayers pgtype.Int4
	GameTypeId pgtype.Int8
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

func (q *Queries) EditGame(ctx context.Context, arg EditGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, editGame,
		arg.ID,
		arg.Name,
		arg.Start,
		arg.Open,
		arg.CardPrice,
		arg.MaxPlayers,
		arg.GameTypeId,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Start,
		&i.Open,
		&i.CardPrice,
		&i.MaxPlayers,
		&i.GameTypeId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGame = `-- name: GetGame :one
SELECT id, name, start, open, "cardPrice", "maxPlayers", "gameTypeId", "createdAt", "updatedAt" FROM game WHERE "id" = $1
`

func (q *Queries) GetGame(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Start,
		&i.Open,
		&i.CardPrice,
		&i.MaxPlayers,
		&i.GameTypeId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
