// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: game.sql

package queries

import (
	"context"
)

const getGameBalls = `-- name: GetGameBalls :many
SELECT id, "gameId", number, "createdAt" FROM "game_ball" WHERE "gameId" = $1 ORDER BY "createdAt" ASC
`

func (q *Queries) GetGameBalls(ctx context.Context, gameid int64) ([]GameBall, error) {
	rows, err := q.db.Query(ctx, getGameBalls, gameid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameBall
	for rows.Next() {
		var i GameBall
		if err := rows.Scan(
			&i.ID,
			&i.GameId,
			&i.Number,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, name, start, open, "cardPrice", "maxPlayers", "gameTypeId", "createdAt", "updatedAt" FROM "game" WHERE "id" = $1 LIMIT 1
`

func (q *Queries) GetGameByID(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Start,
		&i.Open,
		&i.CardPrice,
		&i.MaxPlayers,
		&i.GameTypeId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameCardByUser = `-- name: GetGameCardByUser :one
SELECT id, "userId", "gameId", winner, seed, "createdAt" FROM "game_card" WHERE "gameId" = $1 AND "userId" = $2
`

type GetGameCardByUserParams struct {
	GameId int64
	UserId int64
}

func (q *Queries) GetGameCardByUser(ctx context.Context, arg GetGameCardByUserParams) (GameCard, error) {
	row := q.db.QueryRow(ctx, getGameCardByUser, arg.GameId, arg.UserId)
	var i GameCard
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.GameId,
		&i.Winner,
		&i.Seed,
		&i.CreatedAt,
	)
	return i, err
}

const getGameCards = `-- name: GetGameCards :many
SELECT id, "userId", "gameId", winner, seed, "createdAt" FROM "game_card" WHERE "gameId" = $1
`

func (q *Queries) GetGameCards(ctx context.Context, gameid int64) ([]GameCard, error) {
	rows, err := q.db.Query(ctx, getGameCards, gameid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameCard
	for rows.Next() {
		var i GameCard
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.GameId,
			&i.Winner,
			&i.Seed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameWinner = `-- name: GetGameWinner :one
SELECT id, "userId", "gameId", winner, seed, "createdAt" FROM "game_card" WHERE "gameId" = $1 AND "winner" = true
`

func (q *Queries) GetGameWinner(ctx context.Context, gameid int64) (GameCard, error) {
	row := q.db.QueryRow(ctx, getGameWinner, gameid)
	var i GameCard
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.GameId,
		&i.Winner,
		&i.Seed,
		&i.CreatedAt,
	)
	return i, err
}

const listGames = `-- name: ListGames :many
SELECT id, name, start, open, "cardPrice", "maxPlayers", "gameTypeId", "createdAt", "updatedAt" FROM "game" ORDER BY "createdAt" DESC
`

func (q *Queries) ListGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Start,
			&i.Open,
			&i.CardPrice,
			&i.MaxPlayers,
			&i.GameTypeId,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
