// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string
	AccountId             string
	ProviderId            string
	UserId                string
	AccessToken           pgtype.Text
	RefreshToken          pgtype.Text
	IdToken               pgtype.Text
	AccessTokenExpiresAt  pgtype.Timestamp
	RefreshTokenExpiresAt pgtype.Timestamp
	Scope                 pgtype.Text
	Password              pgtype.Text
	CreatedAt             pgtype.Timestamp
	UpdatedAt             pgtype.Timestamp
}

type Jwk struct {
	ID         string
	PublicKey  string
	PrivateKey string
	CreatedAt  pgtype.Timestamp
}

type Session struct {
	ID        string
	ExpiresAt pgtype.Timestamp
	Token     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	UserId    string
}

type User struct {
	ID            string
	Name          string
	Email         string
	EmailVerified bool
	Image         pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type Verification struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
