// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package queries

import (
	"context"
)

const addPaymentMethodWithUserID = `-- name: AddPaymentMethodWithUserID :exec
INSERT INTO "payment_method" ("userId", "methodTypeId", "data") VALUES ($1, $2, $3)
`

type AddPaymentMethodWithUserIDParams struct {
	UserId       int64
	MethodTypeId int64
	Data         []byte
}

func (q *Queries) AddPaymentMethodWithUserID(ctx context.Context, arg AddPaymentMethodWithUserIDParams) error {
	_, err := q.db.Exec(ctx, addPaymentMethodWithUserID, arg.UserId, arg.MethodTypeId, arg.Data)
	return err
}

const getPaymentMethodsByUserID = `-- name: GetPaymentMethodsByUserID :many
SELECT id, "userId", "methodTypeId", data FROM "payment_method" WHERE "userId" = $1
`

func (q *Queries) GetPaymentMethodsByUserID(ctx context.Context, userid int64) ([]PaymentMethod, error) {
	rows, err := q.db.Query(ctx, getPaymentMethodsByUserID, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentMethod
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.MethodTypeId,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, "emailVerified", role, banned, "banReason", "banExpires", image, "createdAt", "updatedAt" FROM "user" WHERE "id" = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Role,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
