// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/user/user.proto

package userconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	user "github.com/Gabo-div/bingo/packages/protobuf/go/proto/user"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "user.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceGetUserProcedure is the fully-qualified name of the UserService's GetUser RPC.
	UserServiceGetUserProcedure = "/user.UserService/GetUser"
	// UserServiceAddPaymentMethodProcedure is the fully-qualified name of the UserService's
	// AddPaymentMethod RPC.
	UserServiceAddPaymentMethodProcedure = "/user.UserService/AddPaymentMethod"
	// UserServiceGetPaymentMethodsProcedure is the fully-qualified name of the UserService's
	// GetPaymentMethods RPC.
	UserServiceGetPaymentMethodsProcedure = "/user.UserService/GetPaymentMethods"
)

// UserServiceClient is a client for the user.UserService service.
type UserServiceClient interface {
	GetUser(context.Context, *connect.Request[user.Empty]) (*connect.Response[user.User], error)
	AddPaymentMethod(context.Context, *connect.Request[user.PaymentMethodReq]) (*connect.Response[user.Empty], error)
	GetPaymentMethods(context.Context, *connect.Request[user.Empty]) (*connect.Response[user.PaymentMethodList], error)
}

// NewUserServiceClient constructs a client for the user.UserService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := user.File_proto_user_user_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		getUser: connect.NewClient[user.Empty, user.User](
			httpClient,
			baseURL+UserServiceGetUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		addPaymentMethod: connect.NewClient[user.PaymentMethodReq, user.Empty](
			httpClient,
			baseURL+UserServiceAddPaymentMethodProcedure,
			connect.WithSchema(userServiceMethods.ByName("AddPaymentMethod")),
			connect.WithClientOptions(opts...),
		),
		getPaymentMethods: connect.NewClient[user.Empty, user.PaymentMethodList](
			httpClient,
			baseURL+UserServiceGetPaymentMethodsProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetPaymentMethods")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	getUser           *connect.Client[user.Empty, user.User]
	addPaymentMethod  *connect.Client[user.PaymentMethodReq, user.Empty]
	getPaymentMethods *connect.Client[user.Empty, user.PaymentMethodList]
}

// GetUser calls user.UserService.GetUser.
func (c *userServiceClient) GetUser(ctx context.Context, req *connect.Request[user.Empty]) (*connect.Response[user.User], error) {
	return c.getUser.CallUnary(ctx, req)
}

// AddPaymentMethod calls user.UserService.AddPaymentMethod.
func (c *userServiceClient) AddPaymentMethod(ctx context.Context, req *connect.Request[user.PaymentMethodReq]) (*connect.Response[user.Empty], error) {
	return c.addPaymentMethod.CallUnary(ctx, req)
}

// GetPaymentMethods calls user.UserService.GetPaymentMethods.
func (c *userServiceClient) GetPaymentMethods(ctx context.Context, req *connect.Request[user.Empty]) (*connect.Response[user.PaymentMethodList], error) {
	return c.getPaymentMethods.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the user.UserService service.
type UserServiceHandler interface {
	GetUser(context.Context, *connect.Request[user.Empty]) (*connect.Response[user.User], error)
	AddPaymentMethod(context.Context, *connect.Request[user.PaymentMethodReq]) (*connect.Response[user.Empty], error)
	GetPaymentMethods(context.Context, *connect.Request[user.Empty]) (*connect.Response[user.PaymentMethodList], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := user.File_proto_user_user_proto.Services().ByName("UserService").Methods()
	userServiceGetUserHandler := connect.NewUnaryHandler(
		UserServiceGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(userServiceMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceAddPaymentMethodHandler := connect.NewUnaryHandler(
		UserServiceAddPaymentMethodProcedure,
		svc.AddPaymentMethod,
		connect.WithSchema(userServiceMethods.ByName("AddPaymentMethod")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetPaymentMethodsHandler := connect.NewUnaryHandler(
		UserServiceGetPaymentMethodsProcedure,
		svc.GetPaymentMethods,
		connect.WithSchema(userServiceMethods.ByName("GetPaymentMethods")),
		connect.WithHandlerOptions(opts...),
	)
	return "/user.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceGetUserProcedure:
			userServiceGetUserHandler.ServeHTTP(w, r)
		case UserServiceAddPaymentMethodProcedure:
			userServiceAddPaymentMethodHandler.ServeHTTP(w, r)
		case UserServiceGetPaymentMethodsProcedure:
			userServiceGetPaymentMethodsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) GetUser(context.Context, *connect.Request[user.Empty]) (*connect.Response[user.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.UserService.GetUser is not implemented"))
}

func (UnimplementedUserServiceHandler) AddPaymentMethod(context.Context, *connect.Request[user.PaymentMethodReq]) (*connect.Response[user.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.UserService.AddPaymentMethod is not implemented"))
}

func (UnimplementedUserServiceHandler) GetPaymentMethods(context.Context, *connect.Request[user.Empty]) (*connect.Response[user.PaymentMethodList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.UserService.GetPaymentMethods is not implemented"))
}
