// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file proto/game/game.proto (package game, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/game/game.proto.
 */
export const file_proto_game_game: GenFile = /*@__PURE__*/
  fileDesc("ChVwcm90by9nYW1lL2dhbWUucHJvdG8SBGdhbWUiVAoJR2FtZUJvYXJkEgwKBHNlZWQYASABKAMSIQoEY29scxgCIAMoCzITLmdhbWUuR2FtZUJvYXJkLlJvdxoWCgNSb3cSDwoHbnVtYmVycxgBIAMoDSInChVHZW5lcmF0ZUJvYXJkc1JlcXVlc3QSDgoGbnVtYmVyGAEgASgNIjkKFkdlbmVyYXRlQm9hcmRzUmVzcG9uc2USHwoGYm9hcmRzGAEgAygLMg8uZ2FtZS5HYW1lQm9hcmQyWgoLR2FtZVNlcnZpY2USSwoOR2VuZXJhdGVCb2FyZHMSGy5nYW1lLkdlbmVyYXRlQm9hcmRzUmVxdWVzdBocLmdhbWUuR2VuZXJhdGVCb2FyZHNSZXNwb25zZUJAWj5naXRodWIuY29tL0dhYm8tZGl2L2JpbmdvL3BhY2thZ2VzL3Byb3RvYnVmL2dvL3Byb3RvL2dhbWU7Z2FtZWIGcHJvdG8z");

/**
 * @generated from message game.GameBoard
 */
export type GameBoard = Message<"game.GameBoard"> & {
  /**
   * @generated from field: int64 seed = 1;
   */
  seed: bigint;

  /**
   * @generated from field: repeated game.GameBoard.Row cols = 2;
   */
  cols: GameBoard_Row[];
};

/**
 * Describes the message game.GameBoard.
 * Use `create(GameBoardSchema)` to create a new message.
 */
export const GameBoardSchema: GenMessage<GameBoard> = /*@__PURE__*/
  messageDesc(file_proto_game_game, 0);

/**
 * @generated from message game.GameBoard.Row
 */
export type GameBoard_Row = Message<"game.GameBoard.Row"> & {
  /**
   * @generated from field: repeated uint32 numbers = 1;
   */
  numbers: number[];
};

/**
 * Describes the message game.GameBoard.Row.
 * Use `create(GameBoard_RowSchema)` to create a new message.
 */
export const GameBoard_RowSchema: GenMessage<GameBoard_Row> = /*@__PURE__*/
  messageDesc(file_proto_game_game, 0, 0);

/**
 * @generated from message game.GenerateBoardsRequest
 */
export type GenerateBoardsRequest = Message<"game.GenerateBoardsRequest"> & {
  /**
   * @generated from field: uint32 number = 1;
   */
  number: number;
};

/**
 * Describes the message game.GenerateBoardsRequest.
 * Use `create(GenerateBoardsRequestSchema)` to create a new message.
 */
export const GenerateBoardsRequestSchema: GenMessage<GenerateBoardsRequest> = /*@__PURE__*/
  messageDesc(file_proto_game_game, 1);

/**
 * @generated from message game.GenerateBoardsResponse
 */
export type GenerateBoardsResponse = Message<"game.GenerateBoardsResponse"> & {
  /**
   * @generated from field: repeated game.GameBoard boards = 1;
   */
  boards: GameBoard[];
};

/**
 * Describes the message game.GenerateBoardsResponse.
 * Use `create(GenerateBoardsResponseSchema)` to create a new message.
 */
export const GenerateBoardsResponseSchema: GenMessage<GenerateBoardsResponse> = /*@__PURE__*/
  messageDesc(file_proto_game_game, 2);

/**
 * @generated from service game.GameService
 */
export const GameService: GenService<{
  /**
   * @generated from rpc game.GameService.GenerateBoards
   */
  generateBoards: {
    methodKind: "unary";
    input: typeof GenerateBoardsRequestSchema;
    output: typeof GenerateBoardsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_game_game, 0);

