// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/game/game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameBoard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          int64                  `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Cols          []*GameBoard_Row       `protobuf:"bytes,2,rep,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameBoard) Reset() {
	*x = GameBoard{}
	mi := &file_proto_game_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameBoard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameBoard) ProtoMessage() {}

func (x *GameBoard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameBoard.ProtoReflect.Descriptor instead.
func (*GameBoard) Descriptor() ([]byte, []int) {
	return file_proto_game_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameBoard) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *GameBoard) GetCols() []*GameBoard_Row {
	if x != nil {
		return x.Cols
	}
	return nil
}

type GenerateBoardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint32                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateBoardsRequest) Reset() {
	*x = GenerateBoardsRequest{}
	mi := &file_proto_game_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateBoardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateBoardsRequest) ProtoMessage() {}

func (x *GenerateBoardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateBoardsRequest.ProtoReflect.Descriptor instead.
func (*GenerateBoardsRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_game_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateBoardsRequest) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GenerateBoardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boards        []*GameBoard           `protobuf:"bytes,1,rep,name=boards,proto3" json:"boards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateBoardsResponse) Reset() {
	*x = GenerateBoardsResponse{}
	mi := &file_proto_game_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateBoardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateBoardsResponse) ProtoMessage() {}

func (x *GenerateBoardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateBoardsResponse.ProtoReflect.Descriptor instead.
func (*GenerateBoardsResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_game_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateBoardsResponse) GetBoards() []*GameBoard {
	if x != nil {
		return x.Boards
	}
	return nil
}

type GameBoard_Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numbers       []uint32               `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameBoard_Row) Reset() {
	*x = GameBoard_Row{}
	mi := &file_proto_game_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameBoard_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameBoard_Row) ProtoMessage() {}

func (x *GameBoard_Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameBoard_Row.ProtoReflect.Descriptor instead.
func (*GameBoard_Row) Descriptor() ([]byte, []int) {
	return file_proto_game_game_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GameBoard_Row) GetNumbers() []uint32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

var File_proto_game_game_proto protoreflect.FileDescriptor

const file_proto_game_game_proto_rawDesc = "" +
	"\n" +
	"\x15proto/game/game.proto\x12\x04game\"i\n" +
	"\tGameBoard\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\x03R\x04seed\x12'\n" +
	"\x04cols\x18\x02 \x03(\v2\x13.game.GameBoard.RowR\x04cols\x1a\x1f\n" +
	"\x03Row\x12\x18\n" +
	"\anumbers\x18\x01 \x03(\rR\anumbers\"/\n" +
	"\x15GenerateBoardsRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\rR\x06number\"A\n" +
	"\x16GenerateBoardsResponse\x12'\n" +
	"\x06boards\x18\x01 \x03(\v2\x0f.game.GameBoardR\x06boards2Z\n" +
	"\vGameService\x12K\n" +
	"\x0eGenerateBoards\x12\x1b.game.GenerateBoardsRequest\x1a\x1c.game.GenerateBoardsResponseB@Z>github.com/Gabo-div/bingo/packages/protobuf/go/proto/game;gameb\x06proto3"

var (
	file_proto_game_game_proto_rawDescOnce sync.Once
	file_proto_game_game_proto_rawDescData []byte
)

func file_proto_game_game_proto_rawDescGZIP() []byte {
	file_proto_game_game_proto_rawDescOnce.Do(func() {
		file_proto_game_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_game_proto_rawDesc), len(file_proto_game_game_proto_rawDesc)))
	})
	return file_proto_game_game_proto_rawDescData
}

var file_proto_game_game_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_game_game_proto_goTypes = []any{
	(*GameBoard)(nil),              // 0: game.GameBoard
	(*GenerateBoardsRequest)(nil),  // 1: game.GenerateBoardsRequest
	(*GenerateBoardsResponse)(nil), // 2: game.GenerateBoardsResponse
	(*GameBoard_Row)(nil),          // 3: game.GameBoard.Row
}
var file_proto_game_game_proto_depIdxs = []int32{
	3, // 0: game.GameBoard.cols:type_name -> game.GameBoard.Row
	0, // 1: game.GenerateBoardsResponse.boards:type_name -> game.GameBoard
	1, // 2: game.GameService.GenerateBoards:input_type -> game.GenerateBoardsRequest
	2, // 3: game.GameService.GenerateBoards:output_type -> game.GenerateBoardsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_game_game_proto_init() }
func file_proto_game_game_proto_init() {
	if File_proto_game_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_game_proto_rawDesc), len(file_proto_game_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_game_game_proto_goTypes,
		DependencyIndexes: file_proto_game_game_proto_depIdxs,
		MessageInfos:      file_proto_game_game_proto_msgTypes,
	}.Build()
	File_proto_game_game_proto = out.File
	file_proto_game_game_proto_goTypes = nil
	file_proto_game_game_proto_depIdxs = nil
}
